server:
  # http端口号
  port: 8080
  servlet:
    # 路由前缀
    context-path: /docc

spring:
  mvc:
    # 兼容Swagger3
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    # 中台名称
    name: docc-document-center

  # 数据源配置（默认使用mariadb，也可换成mysql，两者通用）
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/docc_document_center_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

# elasticsearch配置
elasticsearch:
  # 集群配置：http://127.0.0.1:9200,http://127.0.0.2:9200,http://127.0.0.3:9200 逗号间隔
  url: http://127.0.0.1:9200
  username: elastic
  password:
  # 索引名称
  indexName: docc-document-center-product

# 集群配置（涉及雪花id生成）
cluster:
  # 数据中心id
  datacenterId: 1
  # 机器id
  workerId: 0

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    # 使用jdbc的getGenerateKeys获取数据库自增主键值
    use-generated-keys: true
    # 使用列标签替换列别名 默认true
    use-column-label: true
    # 开启驼峰命名转换：Table{create_time} -> Entity{createTime}
    map-underscore-to-camel-case: true

# 乐观锁配置
optimistic:
  # 更新失败-重试次数
  update:
    retry: 20